theme = "Kobo Kanaeru Cursor"
sizes = [32, 48, 64, 96]

[[cursor]]
name = "default"
aliases = ["arrow", "left_ptr", "top_left_arrow", "X_cursor", "mouse"]
input = "Kobo normal.ani"

[[cursor]]
name = "help"
aliases = ["question_arrow", "whats_this", "left_ptr_help", "5c6cd98b3f3ebcb1f9c7f1c204630408", "d9ce0ab605698f320427677b458ad60b"]
input = "Kobo help.ani"

[[cursor]]
name = "progress"
aliases = ["half-busy", "left_ptr_watch", "3ecb610c1bf2410f44200f48c40d3599", "08e8e1c95fe2fc01f976f1e063a24ccd", "00000000000000020006000e7e9ffc3f"]
input = "Kobo work.ani"

[[cursor]]
name = "wait"
aliases = ["watch"]
input = "Kobo busy.ani"

[[cursor]]
name = "crosshair"
aliases = ["cross", "cross_reverse", "diamond_cross", "tcross", "plus"]
input = "Kobo precision.ani"

[[cursor]]
name = "text"
aliases = ["xterm", "ibeam"]
input = "Kobo text.ani"

[[cursor]]
name = "hand"
aliases = ["pencil", "draft"]
input = "Kobo hand.ani"

[[cursor]]
name = "unavailable"
aliases = ["not-allowed", "no-drop", "dnd-no-drop", "circle", "crossed_circle", "forbidden", "03b6e0fcb3499374a867c041f52298f0"]
input = "Kobo unavailable.ani"

[[cursor]]
name = "ns-resize"
aliases = ["top_side", "bottom_side", "n-resize", "s-resize", "row-resize", "size_ver", "size-ver", "split_v", "double_arrow", "v_double_arrow", "sb_v_double_arrow", "00008160000006810000408080010102", "2870a09082c103050810ffdffffe0204"]
input = "Kobo vert.ani"

[[cursor]]
name = "ew-resize"
aliases = ["left_side", "right_side", "sb_h_double_arrow", "w-resize", "e-resize", "size_hor", "h_double_arrow", "size-hor", "col-resize", "split_h", "14fef782d02440884392942c11205230", "028006030e0e7ebffc7f7070c0600140"]
input = "Kobo horz.ani"

[[cursor]]
name = "nwse-resize"
aliases = ["bd_double_arrow", "bottom_right_corner", "top_left_corner", "se-resize", "nw-resize", "size_fdiag"]
input = "Kobo dgn1.ani"

[[cursor]]
name = "nesw-resize"
aliases = ["bottom_left_corner", "fd_double_arrow", "top_right_corner", "sw-resize", "ne-resize", "size_bdiag", "size-bdiag", "fcf1c3c7cd4491d801f1e1c78f100000"]
input = "Kobo dgn2.ani"

[[cursor]]
name = "move"
aliases = ["cell", "fleur", "size_all", "all-scroll", "grabbing", "closedhand", "dnd-move", "dnd-none", "dnd-ask", "4498f0e0c1937ffe01fd06f973665830", "9081237383d90e509aa00f00170e968f", "fcf21c00b30f7e3f83fe0dfd12e71cff"]
input = "Kobo move.ani"

[[cursor]]
name = "alternate"
aliases = ["alias", "up_arrow"]
input = "Kobo alt.ani"

[[cursor]]
name = "link"
aliases = ["pointer", "pointing_hand", "hand1", "hand2", "9d800788f1b08800ae810202380a0822", "e29285e634086352946a0e7090d73106"]
input = "Kobo link.ani"

[[cursor]]
name = "pin"
aliases = []
input = "Kobo location.ani"

[[cursor]]
name = "person"
aliases = []
input = "Kobo person.ani"
